### ISSUE TITLE
Scrollbar isnt there

### ISSUE THREAD

**Issue by ghost** [jko64/RETROtube#3]
the scrollbar is gone and it's hard to scroll without a mouse
(you can use the 2 finger scroll though lmao i forgot how it's called)
OS: Linux Mint 20.3 
Browser: Chrome beta version 99.0.4844.27
How to reproduce: Go to the homepage

**Comment by ghost** [comment]
okay

**Comment by ghost** [comment]
i mean, it's not really a problem.

**Comment by ghost** [comment]
prob made because of *cough* css *cough* pain

**Comment by jkosixtyfour** [comment]
yeah I noticed so I'll check the css

**Comment by jkosixtyfour** [comment]
problem with your chrome install
im using chrome 98.0.4758.102 on windows 10 ltsc 1809 and it fine so um
